trigger: 
 - master

pool:
   vmImage: 'vs2017-win2016'

steps: 
- task: GoTool@0
  inputs:
    version: '1.14.7'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    arguments: '-o azure-devops-ci-lab.exe'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: ArchiveFiles@2
  displayName: 'archive files'
  inputs:
     rootFolderOrFile: '$(Build.Repository.LocalPath)'
     includeRootFolder: False 
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop